export const Facilitors = [
  {
    id: 1,
    profile: "/profile.png",
    name: "cinta castella",
    course: "javascript",
    class: "year 1",
    emailAdress: "test@gmail.com",
    description:
      "Nulla Lorem mollit cupidatat irure. Laborum magna nulla duis ullamco cillum dolor. Voluptate exercitation incididunt aliquip deserunt reprehenderit elit laborum. Nulla Lorem mollit cupidatat irure. Laborum magna nulla duis ullamco cillum dolor. Voluptate exercitation incididunt aliquip deserunt reprehenderit elit laborum. ",
    gender: "female",
    age: 40,
    phoneNo: 782323232,
    address: "kigali",
  },
  {
    id: 2,
    profile: "/profile.png",
    name: "cinta castella",
    course: "javascript",
    class: "year 1",
    description:
    "Nulla Lorem mollit cupidatat irure. Laborum magna nulla duis ullamco cillum dolor. Voluptate exercitation incididunt aliquip deserunt reprehenderit elit laborum. Nulla Lorem mollit cupidatat irure. Laborum magna nulla duis ullamco cillum dolor. Voluptate exercitation incididunt aliquip deserunt reprehenderit elit laborum. ",
    emailAdress: "test@gmail.com",
    gender: "female",
    age: 40,
    phoneNo: 782323232,
    address: "kigali",
  },
  {
    id: 3,
    profile: "/profile.png",
    name: "cinta castella",
    course: "javascript",
    description:
    "Nulla Lorem mollit cupidatat irure. Laborum magna nulla duis ullamco cillum dolor. Voluptate exercitation incididunt aliquip deserunt reprehenderit elit laborum. Nulla Lorem mollit cupidatat irure. Laborum magna nulla duis ullamco cillum dolor. Voluptate exercitation incididunt aliquip deserunt reprehenderit elit laborum. ",
    class: "year 1",
    emailAdress: "test@gmail.com",
    gender: "female",
    age: 40,
    phoneNo: 782323232,
    address: "kigali",
  },
  {
    id: 4,
    profile: "/profile.png",
    name: "cinta castella",
    course: "javascript",
    class: "year 1",
    description:
    "Nulla Lorem mollit cupidatat irure. Laborum magna nulla duis ullamco cillum dolor. Voluptate exercitation incididunt aliquip deserunt reprehenderit elit laborum. Nulla Lorem mollit cupidatat irure. Laborum magna nulla duis ullamco cillum dolor. Voluptate exercitation incididunt aliquip deserunt reprehenderit elit laborum. ",
    emailAdress: "test@gmail.com",
    gender: "female",
    age: 40,
    phoneNo: 782323232,
    address: "kigali",
  },
  {
    id: 5,
    profile: "/student.svg",
    name: "cinta castella",
    course: "javascript",
    class: "year 1",
    description:
    "Nulla Lorem mollit cupidatat irure. Laborum magna nulla duis ullamco cillum dolor. Voluptate exercitation incididunt aliquip deserunt reprehenderit elit laborum. Nulla Lorem mollit cupidatat irure. Laborum magna nulla duis ullamco cillum dolor. Voluptate exercitation incididunt aliquip deserunt reprehenderit elit laborum. ",
    emailAdress: "test@gmail.com",
    gender: "female",
    age: 40,
    phoneNo: 782323232,
    address: "kigali",
  },
  {
    id: 6,
    profile: "/profile.png",
    name: "prince Rukundo",
    course: "javascript",
    class: "year 1",
    description:
    "Nulla Lorem mollit cupidatat irure. Laborum magna nulla duis ullamco cillum dolor. Voluptate exercitation incididunt aliquip deserunt reprehenderit elit laborum. Nulla Lorem mollit cupidatat irure. Laborum magna nulla duis ullamco cillum dolor. Voluptate exercitation incididunt aliquip deserunt reprehenderit elit laborum. ",
    emailAdress: "test@gmail.com",
    gender: "female",
    age: 40,
    phoneNo: 782323232,
    address: "kigali",
  },
  {
    id: 7,
    profile: "/student.svg",
    name: "cinta castella",
    course: "javascript",
    class: "year 1",
    description:
    "Nulla Lorem mollit cupidatat irure. Laborum magna nulla duis ullamco cillum dolor. Voluptate exercitation incididunt aliquip deserunt reprehenderit elit laborum. Nulla Lorem mollit cupidatat irure. Laborum magna nulla duis ullamco cillum dolor. Voluptate exercitation incididunt aliquip deserunt reprehenderit elit laborum. ",
    emailAdress: "test@gmail.com",
    gender: "female",
    age: 40,
    phoneNo: 782323232,
    address: "kigali",
  },
  {
    id: 8,
    profile: "/profile.png",
    name: "cinta castella",
    course: "javascript",
    class: "year 3",
    description:
    "Nulla Lorem mollit cupidatat irure. Laborum magna nulla duis ullamco cillum dolor. Voluptate exercitation incididunt aliquip deserunt reprehenderit elit laborum. Nulla Lorem mollit cupidatat irure. Laborum magna nulla duis ullamco cillum dolor. Voluptate exercitation incididunt aliquip deserunt reprehenderit elit laborum. ",
    emailAdress: "test@gmail.com",
    gender: "female",
    age: 40,
    phoneNo: 782323232,
    address: "kigali",
  },
  {
    id: 9,
    profile: "/profile.png",
    name: "cinta castella",
    course: "javascript",
    class: "year 1",
    description:
    "Nulla Lorem mollit cupidatat irure. Laborum magna nulla duis ullamco cillum dolor. Voluptate exercitation incididunt aliquip deserunt reprehenderit elit laborum. Nulla Lorem mollit cupidatat irure. Laborum magna nulla duis ullamco cillum dolor. Voluptate exercitation incididunt aliquip deserunt reprehenderit elit laborum. ",
    emailAdress: "test@gmail.com",
    gender: "female",
    age: 40,
    phoneNo: 782323232,
    address: "kigali",
  },
  {
    id: 10,
    profile: "/profile.png",
    name: "cinta castella",
    course: "javascript",
    class: "year 1",
    emailAdress: "test@gmail.com",
    gender: "female",
    description:
      "Nulla Lorem mollit cupidatat irure. Laborum magna nulla duis ullamco cillum dolor. Voluptate exercitation incididunt aliquip deserunt reprehenderit elit laborum. Nulla Lorem mollit cupidatat irure. Laborum magna nulla duis ullamco cillum dolor. Voluptate exercitation incididunt aliquip deserunt reprehenderit elit laborum. ",
    age: 40,
    phoneNo: 782323232,
    address: "kigali",
  },
];
